from argparse import ArgumentParser
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from PIL import Image


DEFAULT_METADATA_PATH = Path("outputs/metadata/train_metadata.csv")
DEFAULT_SAVE_PATH = Path("outputs/metadata/gray_check.png")


def parse_args():
    parser = ArgumentParser(description="Visual check for processed grayscale images.")
    parser.add_argument(
        "--metadata",
        type=Path,
        default=DEFAULT_METADATA_PATH,
        help="Path to the metadata CSV generated by preprocess.py.",
    )
    parser.add_argument(
        "--per-class",
        type=int,
        default=3,
        help="Number of sample images to show for each class.",
    )
    parser.add_argument(
        "--save",
        type=Path,
        default=None,
        help=f"Save the preview image, for example {DEFAULT_SAVE_PATH}.",
    )
    parser.add_argument(
        "--no-show",
        action="store_true",
        help="Do not open an interactive matplotlib window.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    if not args.metadata.exists():
        raise FileNotFoundError(f"Metadata file does not exist: {args.metadata}")

    df = pd.read_csv(args.metadata)
    sample_df = df.groupby("class_name", group_keys=False).head(args.per_class)

    class_count = sample_df["class_name"].nunique()
    rows = max(class_count, 1)
    cols = args.per_class

    plt.figure(figsize=(cols * 2.6, rows * 2.4))

    for i, (_, row) in enumerate(sample_df.iterrows()):
        img = Image.open(row["gray_path"])

        plt.subplot(rows, cols, i + 1)
        plt.imshow(img, cmap="gray")
        plt.title(f'{row["class_name"]} | label={row["label"]}')
        plt.axis("off")

    plt.tight_layout()

    if args.save is not None:
        args.save.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(args.save, dpi=150, bbox_inches="tight")
        print(f"Preview saved to: {args.save}")

    if not args.no_show:
        plt.show()

    plt.close()


if __name__ == "__main__":
    main()
